require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'zeechatapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-bambuser-broadcaster', :path => '../node_modules/react-native-bambuser-broadcaster'

  target 'zeechatappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
    #flipper_post_install(installer)
  #end
end

target 'zeechatapp-tvOS' do
  # Pods for zeechatapp-tvOS

  target 'zeechatapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
